name: ci

on:
  push:
    branches:
      - 'main'
    paths:
      - 'nodes/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches:
      - '**'
    paths:
      - 'nodes/**'
      - '.github/workflows/ci.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - uses: ./.github/actions/setup-bun
      - name: Run build
        run: |
          # Remove extractDataFromResponse.ts file to not fail build
          rm nodes/HeyPocketAi/utils/extractDataFromResponse.test.ts
          bun run build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - uses: ./.github/actions/setup-bun
      - name: Run lint
        run: bun run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - uses: ./.github/actions/setup-bun
      - name: Run tests
        run: bun test
