on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write 

name: Release and Publish

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_TOKEN }}

  npm-publish:
    needs: release-please
    environment:
      name: npm
      url: https://www.npmjs.com/package/n8n-nodes-hey-pocket-ai
    runs-on: ubuntu-latest
    if: needs.release-please.outputs.release_created == 'true'
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - uses: ./.github/actions/setup-bun
      - name: Configure npm auth
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish to npm
        run: |
          # Remove extractDataFromResponse.ts file to not fail build
          rm nodes/HeyPocketAi/utils/extractDataFromResponse.test.ts
          bun run build
          bun run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}